/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -p OfonoManager ofono_main_fmt.xml org.ofono.Manager
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "OfonoManager.h"

// Marshall the OfonoModem data into a D-Bus argument
QDBusArgument &operator<<(QDBusArgument &argument, const OfonoModem &modem)
{
    argument.beginStructure();
    argument << modem.objectPath << modem.properties;
    argument.endStructure();
    return argument;
}

// Retrieve the OfonoModem data from the D-Bus argument
const QDBusArgument &operator>>(const QDBusArgument &argument, OfonoModem &modem)
{
    argument.beginStructure();
    argument >> modem.objectPath >> modem.properties;
    argument.endStructure();
    return argument;
}

/*
 * Implementation of interface class OrgOfonoManagerInterface
 */

OrgOfonoManagerInterface::OrgOfonoManagerInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgOfonoManagerInterface::~OrgOfonoManagerInterface()
{
}

